### ISSUE TITLE
Suggestion: use YAML for bento.info file

### ISSUE THREAD

**Issue by eugene-eeo** [cournape/Bento#142]
The syntax looks very much like YAML, IMHO it is not necessary to create an entire module/component just to parse the `bento.info`. Also it is easier to maintain if you use the YAML library. Some links: [pyyaml](http://pyyaml.org/), [YAML spec](http://www.yaml.org/spec/1.2/spec.html).

**Comment by cournape** [comment]
Hi Eugene. Yes, it looks a lot like yaml (I am familiar with the format). The problem is the support for conditional, though you could argue I could have used a template format, like in salt.

**Comment by eugene-eeo** [comment]
Yup, using a template format sounds better. I've read about people using ERB + YAML, perhaps you could just pre-parse the file for simple prefixes (a la compiler directives) before `load`ing it? I.e. for the conditional example:

``` yaml
Library:
    InstallRequires:
        - docutils
        - sphinx
        #[ if os(windows) ]
        - pywin32
        #[ endif ]
```

I'm a fan of rust so I like those kind of "compiler directives" but any syntax would do the trick.
